POST http://localhost:3003/api/blogs/
content-type: application/json

{
  "title": "Chris' blog",
  "author": "Chris Dodd",
  "url": "www.chrisblog.com",
  "likes": 8
}

###
DELETE http://localhost:3003/api/blogs/601f31000987f004184c29a0


###
PUT http://localhost:3003/api/blogs/6020021acac6a629b41e9d78
content-type: application/json

{
    "likes": 40
}

###
POST http://localhost:3003/api/users/
content-type: application/json

{
  "username": "obij",
  "password": "STACKoverflow*21",
  "name": "Obinna Okafor"
}

###
GET http://localhost:3003/api/users/

###
POST http://localhost:3003/api/blogs
content-type: application/json


{
  "title": "Fine Arts Blog",
  "author": "Chinedu Okeke",
  "url": "www.fineartsblog.com",
  "likes": 24
  
}


###
POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "obij",
  "password": "STACKoverflow*21"
}

###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9iaWoiLCJpZCI6IjYwMjQ5YzliNGRmOTVjMmJmMDRjMjUyNCIsImlhdCI6MTYxMzAxMjE5OH0.DYptcxh8jX5184thvmSXqck-UTVd01y3nla_xS6OUDs

{
  "title": "Farming Blog",
  "author": "Ndubuisi Okonkwo",
  "url": "www.farmingblog.com",
  "likes": 20
  
}

###
DELETE http://localhost:3003/api/blogs/60249da54df95c2bf04c2525
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9iaWoiLCJpZCI6IjYwMjQ5YzliNGRmOTVjMmJmMDRjMjUyNCIsImlhdCI6MTYxMzAxMjE5OH0.DYptcxh8jX5184thvmSXqck-UTVd01y3nla_xS6OUDs
